version: '3'
services:
  app:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - db
  db:
    image: mysql:8.0
    ports:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: historias
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
